service: ucsd-rooms

provider:
  name: aws
  runtime: nodejs6.10 # set node.js runtime
  memorySize: 128 # set the maximum memory of the Lambdas in Megabytes
  timeout: 10 # the timeout is 10 seconds (default is 6 seconds)
  stage: dev # setting the env stage to dev, this will be visible in the routes
  region: us-west-1

functions:
  getRooms:
    handler: handler.getRooms
    events:
      - http:
          path: rooms
          method: get
          cors: true

plugins:
- serverless-offline # adding the plugin to be able to run the offline emulation